### ISSUE TITLE
Unsanitized filename

### ISSUE THREAD

**Issue by chrisgrieser** [inhumantsar/slurp#20]
It appears the file name is not properly sanitized when slurping. While stuff like `/` does not seem to appear for me, I noticed that `#` and various special characters like the middle dot are kept in the file name when for example slurping a github issue.

A `#` in a filename breaks internal links in Obsidian, because the `#` is interpreted as an attempt to link a heading, and thus not considered part of the filename.

**Comment by inhumantsar** [comment]
the [cleanTitle](https://github.com/inhumantsar/slurp/blob/main/src/lib/util.ts#L15-L29) function focuses on characters that are strictly disallowed by Obsidian and the filesystem. 

I'm hesitant to add `#` to that since it's not an overly common character to find in a title, when it is present it seems likely to be fairly critical to the title's meaning (unlike `"` and `:` which are easy to replace without altering their meaning), and `#` is already overloaded in Obsidian between tags and headings.

that said, i'm planning to add some slurp-time options as the next big feature, eg: add/remove tags and override the save location. could add title there as well and have it display a warning if `#` is in the title. something like "Looks like this title has a hash mark in it, if you don't change that then you won't be able to create internal links to this page." 

seems like that might be a good middle ground vs deciding for people what it should be replaced with.

**Comment by chrisgrieser** [comment]
> I'm hesitant to add # to that since it's not an overly common character to find in a title, when it is present it seems likely to be fairly critical to the title's meaning (unlike " and : which are easy to replace without altering their meaning)

Well, that's exactly what the `title` property [I previously suggested is for – to preserve title information not suited for filenames.](https://github.com/inhumantsar/slurp/issues/3#issuecomment-2058665967)

Strictly speaking, the slash `/` usually is even more meaningful than the `#` when it comes to a title, but obviously, it's removed from a filename as well.

>  and # is already overloaded in Obsidian between tags and headings.

Yeah, that's why it should not be used in filenames? Having a `#` in a filename breaks a bunch of Obsidian functionality. If you are conflicted about this, you could make this an opt-in feature and let the users decide for themselves which characters to allow and which not.

**Comment by inhumantsar** [comment]
> Well, that's exactly what the title property I previously suggested is for 

that's a fair point. either way, i'll look into this soonish

**Comment by inhumantsar** [comment]
should be fixed in 0.1.12!
