### ISSUE TITLE
Is there any way to import the special characters without converting them?

### ISSUE THREAD

**Issue by OPEN1004MIND** [inhumantsar/slurp#30]
Good job with the plugin.
I'm using it in parallel with Omnivore.

The original title is "5. (Turning Point)", but when I import it through the plugin, the title is imported with the special characters changed to "5&period; &lpar;Turning Point&rpar;".

Is there any way to import the special characters without converting them?

**Comment by inhumantsar** [comment]
I might be needing a second cup of coffee but aren't those two strings identical? 

To answer your question though: Unfortunately because the title is used as a filename, Slurp has to strip out characters which don't work (or at least are problematic) in filenames on at least one supported operating system.

Once #29 is complete, Slurp will offer a way to set the filename yourself before saving. It will still have the same restrictions, but at least you will be able to pick your own modifications rather than have Slurp blindly remove characters for you.

**Comment by OPEN1004MIND** [comment]
Thank you fast answer.
I also like the idea of being able to edit the title directly.
I will waiting next version.
