### ISSUE TITLE
The template does not seem to apply to the slurp property.

### ISSUE THREAD

**Issue by froses** [inhumantsar/slurp#33]
Hi,

The template does not seem to apply to the “slurp” property. My template is `d|YYYYYYY-MM-DD HH:mm` but Slurp generates `2024-05-19T08:21:08.450Z`. Furthermore, the time is not correct either. At the time of the capture, it was 10:21. I guess it doesn't consider my time zone (Spain) which is GMT +2.

Thanks for your excellent work!

FRA

**Comment by inhumantsar** [comment]
thanks for the report! there's a few things to unpack here:

- `slurped` template settings were indeed being ignored. it's a unique property in that it is only ever using the default and default values weren't run through format parsing. the fix for that will be in the next release.
- `d|YYYYYYY-MM-DD HH:mm` doesn't seem like a [valid format](https://momentjs.com/docs/#/parsing/string-format/). Years typically have 1, 2, or 4 `Y`s. this format string will yield a result like `+0020242024-05-19 12:31`. though if that's what you're after then nevermind!
- timezone-aware dates are finicky in javascript at the best of times. for example, on my linux machine the `slurped` value is my local time but it's GMT on my windows machine. obsidian complicates matters further. if you set the slurped property to a date type in obsidian it will attempt to format it according to obsidian's settings. i spent a lot of time trying to manage those differences early on. i gave up in the end though since so much of it is client specific and it's somewhat tangential to the goal of slurping pages. i would instead recommend playing with the format template (eg: adding `Z` to the template to indicate that it's a GMT time and letting Obsidian format it accordingly, or using the `L` and `LT` format strings to tell Moment to use locale specific formats).

thanks again for the report, i should be able to publish an update later today with the template fix in it. let me know if you still have trouble with it after updating.

**Comment by froses** [comment]
Hi,

Sorry `d|YYYYYYY-MM-DD HH:mm` is a typo… 

And yes, time zones are a headache. I will follow your advice. Thank you so much.

Thanks!

FRA

**Comment by inhumantsar** [comment]
no problem! keep your eyes peeled for that update. i have one or two other things to put into this release but it'll be out soon. i'll leave this issue open until it's out and you have a chance to test it

**Comment by froses** [comment]
I’ll try it as soon as possible. 

Thanks a lot!

FRA

**Comment by inhumantsar** [comment]
sorry that took so long to release! should be fixed in 0.1.12

**Comment by froses** [comment]
Hi, Shaun,

Thanks a lot!

Francesc
